This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./thesis_main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis_main.acn....done (100 entries accepted, 0 rejected).
Sorting entries....done (703 comparisons).
Generating output file thesis_main.acr....done (88 lines written, 0 warnings).
Output written in thesis_main.acr.
Transcript written in thesis_main.alg.
